name: Docker

on:
  push:
  pull_request:
    branches: [ main ]

env:
  PYTH_TAG: mainnet-v2.9.1
  SERUM_TAG: v0.4.1
  DOCKER_REGISTRY: docker.io
  IS_RELEASE: ${{
    startsWith( github.ref, 'refs/tags/devnet-' ) ||
    startsWith( github.ref, 'refs/tags/testnet-' ) ||
    startsWith( github.ref, 'refs/tags/mainnet-' ) }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize Environment
        run: |
          set -eux
          TAG="${GITHUB_REF##*/}"
          IMG="${GITHUB_REPOSITORY##*/}"
          echo "DOCKER_IMAGE=${IMG}:${TAG}" >> "${GITHUB_ENV}"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_IO_USER }}
          password: ${{ secrets.DOCKER_IO_PASS }}
        if: env.IS_RELEASE

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: ${{ env.IS_RELEASE }}
          build-args: |
            PYTH_TAG=${{ env.PYTH_TAG }}
            SERUM_TAG=${{ env.SERUM_TAG }}
          tags: ${{ secrets.DOCKER_IO_USER }}/${{ env.DOCKER_IMAGE }}
